name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Data files
        run: |
          mkdir src/bin/tests/common/data
          head -c 32 /dev/urandom > src/bin/tests/common/data/key_32B.blb
          head -c 16777216 /dev/urandom > src/bin/tests/common/data/texts_16MB.blb

      - name: Build
        run: cargo build --bin dnac --verbose

      - name: Run tests
        run: cargo test --verbose
